######################################################################################################
# File: docker-compose.yml
#
# Author: Emmanuel Taylor
# Created: April 3, 2025
# Modified: April 3, 2025
#
# Description:
#   - Defines services for the Wordle backend and MongoDB using Docker Compose.
#
# Dependences:
#   - MongoDB (Official Docker Image)
#   - Node.js backend as defined in ./wordle-backend/Dockerfile
######################################################################################################

services:
  mongo:
    image: mongo
    container_name: wordle-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./wordle-backend
    container_name: wordle-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - ./wordle-backend/.env
    environment:
      - MONGO_URI=${MONGO_URI_DOCKER}
      - JWT_SECRET=${JWT_SECRET}

  frontend:
    build: ./wordle
    container_name: wordle-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data: